= Advent Of Code (AOC) 2016

== Day 1

There's no grid, no 2D array, no X and Y variables, and no direction. Like.

Did not understand part 2, failing unit tests because i only marked end
positions. Only when i https://goplay.space[turtle graphic'ed] the example it
became clear that all steps count.

== Day 4

Part 2 needs to find sector ID of room "north pole objects". After finding
nothing, dumping all decrypted rooms, grep'ing for "north" one finally finds
the correct room "northpole object storage".

----
BenchmarkDay4Part1
BenchmarkDay4Part1-16                418           2771044 ns/op         1099945 B/op      12315 allocs/op
BenchmarkDay4Part2
BenchmarkDay4Part2-16             270402              4263 ns/op            1610 B/op         19 allocs/op
----

Use a 26 bytes array to count letter occurences instead of a sparse map[byte]uint:

----
BenchmarkDay4Part1
BenchmarkDay4Part1-16                854           1279735 ns/op          217994 B/op       6545 allocs/op
BenchmarkDay4Part2
BenchmarkDay4Part2-16             857664              1381 ns/op             336 B/op         11 allocs/op
----

Part #1 is 100% faster, part #2 300 % faster.

1381 nanoseconds (ns) are 1.4 microseconds (μs).
Light will travel around 500 meters in 1.6 μs.
I mean this is incredibly fast, nay?

Fastest reported times on reddit are 2 ms versus my 1.2 ms, but then those
numbers are from hardware that is at least 4 years older than my MacBook Pro
(16-inch, 2019, 2,4 GHz 8-Core Intel Core i9). I'm rolling my own parser
though, instead of using `scanf(3)` e.a.

== Day 5

----
BenchmarkDay5Part1
BenchmarkDay5Part1-16    	       1	8290784618 ns/op	1741396552 B/op	100409235 allocs/op
BenchmarkDay5Part2
BenchmarkDay5Part2-16    	       1	13266456586 ns/op	2739557288 B/op	157963381 allocs/op
----

Comparing the binary MD5 instead of the hex representation:

----
BenchmarkDay5Part1
BenchmarkDay5Part1-16    	       1	4014164864 ns/op	669773280 B/op	50204243 allocs/op
BenchmarkDay5Part2
BenchmarkDay5Part2-16    	       1	6278619828 ns/op	1053675720 B/op	78981141 allocs/op
----

Twice as fast,  `benchstat` reports:

----
name          old time/op    new time/op    delta
Day5Part1-16     8.29s ± 0%     4.01s ± 0%   ~     (p=1.000 n=1+1)
Day5Part2-16     13.3s ± 0%      6.3s ± 0%   ~     (p=1.000 n=1+1)

name          old alloc/op   new alloc/op   delta
Day5Part1-16    1.74GB ± 0%    0.67GB ± 0%   ~     (p=1.000 n=1+1)
Day5Part2-16    2.74GB ± 0%    1.05GB ± 0%   ~     (p=1.000 n=1+1)

name          old allocs/op  new allocs/op  delta
Day5Part1-16      100M ± 0%       50M ± 0%   ~     (p=1.000 n=1+1)
Day5Part2-16      158M ± 0%       79M ± 0%   ~     (p=1.000 n=1+1)
----

== Day 11

Now this puzzle is way beyond my capabilities, types of generators do not
matter, never heard of Zobrist before, and the h() function for floors (1 * 
first floor, 2 * second floor, 3 * third floor, 4 * fourth floor) reminds me of
Columbus' egg: simple and easy after the fact.

== Day 13

Off by one for part 2, because 50 steps means the starting point and from then
on 50 steps.
I took the starting point as the first step.

== Day 16

As a bit of surprise, this one was pretty straightforward, first shot ran in
half a second, so no further optimizations such as reducing allocations,
collapsing distinct reverse and flip phases into one e.a.

== Day 17

Both part 1 and part 2 correct on first try.
Updated Go from 1.13 to 1.21 because it is October 2023.

== Day 18


Both part 1 and part 2 correct on first try.
Part 2 is the quickest implementation of any puzzle i have ever done.
I basically just copied the test for part 1 into part 2, ran like a charm.

----
% go test -run=xxx -bench=Day18 -benchmem
goos: darwin
goarch: amd64
pkg: gitlab.com/jhinrichsen/adventofcode2016
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkDay18Part2-16    	       3	 373477125 ns/op	134400981 B/op	 1200004 allocs/op
PASS
ok  	gitlab.com/jhinrichsen/adventofcode2016	2.419
----

Let's see 373477125 ns/op = 373477 μs/op = 373 ms/op.


== Benchmarks


=== Go 1.16.6

go test -run NONE -bench . -benchmem
goos: darwin
goarch: amd64
pkg: gitlab.com/jhinrichsen/adventofcode2016
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkDay10Part1-16                	    7935	    149868 ns/op	  150914 B/op	     898 allocs/op
BenchmarkDay10Part2-16                	    5566	    180755 ns/op	  150906 B/op	     898 allocs/op
BenchmarkDay12Part1-16                	      16	  64670795 ns/op	35622124 B/op	  954128 allocs/op
BenchmarkDay12Part2-16                	       1	1880828079 ns/op	1033513760 B/op	27683214 allocs/op
BenchmarkDay13Part1-16                	   13106	     88480 ns/op	  145743 B/op	     505 allocs/op
BenchmarkDay14Part1-16                	      18	  61525941 ns/op	 3397745 B/op	   78431 allocs/op
BenchmarkDay15Part1PlainVanilla-16    	    3597	    341104 ns/op	       0 B/op	       0 allocs/op
BenchmarkDay15Part2PlainVanilla-16    	     216	   5890262 ns/op	       0 B/op	       0 allocs/op
BenchmarkDay1Part1-16                 	  125259	      8485 ns/op	    3082 B/op	       5 allocs/op
BenchmarkDay1Part2-16                 	   13448	     88505 ns/op	   49126 B/op	      51 allocs/op
BenchmarkDay2Part1-16                 	    9693	    118226 ns/op	     328 B/op	       2 allocs/op
BenchmarkDay2Part2-16                 	    8084	    131257 ns/op	     387 B/op	       3 allocs/op
BenchmarkDay3Part1-16                 	    5994	    208099 ns/op	   91296 B/op	    1902 allocs/op
BenchmarkDay3Part2-16                 	    5872	    208013 ns/op	   91296 B/op	    1902 allocs/op
BenchmarkDay4Part1-16                 	     914	   1284869 ns/op	  210504 B/op	    6545 allocs/op
BenchmarkDay4Part2-16                 	  808363	      1416 ns/op	     328 B/op	      11 allocs/op
BenchmarkDay5Part1-16                 	       1	3987839685 ns/op	669767480 B/op	50204193 allocs/op
BenchmarkDay5Part2-16                 	       1	6387133445 ns/op	1053682040 B/op	78981164 allocs/op
BenchmarkDay6Part1-16                 	  248094	      4243 ns/op	       8 B/op	       1 allocs/op
BenchmarkDay6Part2-16                 	  262150	      4339 ns/op	       8 B/op	       1 allocs/op
BenchmarkDay7Part1-16                 	    1296	    915176 ns/op	  735616 B/op	   14392 allocs/op
BenchmarkDay7Part2-16                 	     559	   2165888 ns/op	 1969477 B/op	   24375 allocs/op
BenchmarkDay8Part1-16                 	   31016	     38769 ns/op	    5648 B/op	     113 allocs/op
BenchmarkDay9Part1-16                 	   35505	     34320 ns/op	       0 B/op	       0 allocs/op
BenchmarkDay9Part2-16                 	   14134	     93560 ns/op	   98304 B/op	       1 allocs/op
PASS

